variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository
    - target/

.verify: &verify
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master

verify:jdk8:
  <<: *verify

deploy_develop:
  stage: deploy
  script:
    - 'mvn clean package -DattachMuleSources deploy:deploy mule:deploy -DENV=Development -DAppEnv=dev'
  only:
    - develop

deploy_test:
  stage: deploy
  script:
    - 'mvn clean package -DattachMuleSources deploy:deploy mule:deploy -DENV=Test -DAppEnv=tst'
  only:
    - test